### ISSUE TITLE
Error while deploying using github to heroku

### ISSUE THREAD

**Issue by mr-antisecurity** [XcodersHub/TorrentLeechX#1]
I followed the guide but deloyment failed:
Run akhileshns/heroku-deploy@v3.12.12
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
 ▸    not logged in
Error: Error: Command failed: heroku container:login
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
 ▸    not logged in

**Comment by chiefgamer** [comment]
Try revoking Heroku api and update the api var

**Comment by AmirulAndalib** [comment]
> I followed the guide but deloyment failed:
> Run akhileshns/heroku-deploy@v3.12.12
> Created and wrote to ~/.netrc
> › Warning: Our terms of service have changed:
> › https://dashboard.heroku.com/terms-of-service
> ▸ not logged in
> Error: Error: Command failed: heroku container:login
> › Warning: Our terms of service have changed:
> › https://dashboard.heroku.com/terms-of-service
> ▸ not logged in

## i think you added environements instead of secrets please check it once more

**Comment by mr-antisecurity** [comment]
> > I followed the guide but deloyment failed:
> > Run akhileshns/heroku-deploy@v3.12.12
> > Created and wrote to ~/.netrc
> > › Warning: Our terms of service have changed:
> > › https://dashboard.heroku.com/terms-of-service
> > ▸ not logged in
> > Error: Error: Command failed: heroku container:login
> > › Warning: Our terms of service have changed:
> > › https://dashboard.heroku.com/terms-of-service
> > ▸ not logged in
> 
> ## i think you added environements instead of secrets please check it once more

Oh yes yes bro sorry :( Now I redeployed fixing it and it is working now. So I'm closing this issue, thanks for the solution.

**Comment by 1xo2** [comment]
go to your Heroku account and go to Account Settings. Scroll to the bottom until you see API Key. Copy this key and go to your project's repository on GitHub.

In your Repo, go to Settings -> Secrets and click on "New Secret". Then enter HEROKU_API_KEY as the name and paste the copied API Key as the value.


name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: "YOUR EMAIL"

https://github.com/marketplace/actions/deploy-to-heroku#deploy-with-docker
